### ISSUE TITLE
.env files aren't .env files!

### ISSUE THREAD

**Issue by judy2k** [Nexmo/nexmo-python-code-snippets#9]
The way we load .env files requires them to be valid *python* code, instead of valid *.env* files. Although there is an overlap in compatibility, these are not the same and so something like [python-dotenv](https://pypi.python.org/pypi/python-dotenv) should be used for parsing this instead.

**Comment by TheGamer007** [comment]
@judy2k is this issue still open? From what I can gather, the requirement is to use python-dotenv to load the `.env` file in `server.py` rather than using Flask's `config.from_pyfile`, similar to how it has been done in some of the examples (like [this one](https://github.com/nexmo-community/nexmo-python-quickstart/blob/master/number-insight/ni-advanced.py#L6)) ? Should I send a PR with those changes?
